

export const CREATE_STUDENT="CREATE_STUDENT";
export const DELETE_STUDENT="DELETE_STUDENT";
export const UPDATE_STUDENT="UPDATE_STUDENT";

export const CREATE_TEACHER="CREATE_TEACHER";
export const DELETE_TEACHER="DELETE_TEACHER";
export const UPDATE_TEACHER="UPDATE_TEACHER";